CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_PERIPHERAL=n
CONFIG_BT_BONDABLE=y
CONFIG_BT_FIXED_PASSKEY=123456
CONFIG_BT_USE_DEBUG_KEYS=y
CONFIG_BT_MAX_CONN=2
CONFIG_BT_MAX_PAIRED=2
